Repository Kernel360/hackathon2-gyeonggiBus, pull requests merged in 2024-07, with the labels that each got.

#17 feat: 프로젝트 초기 설정
  .env.sample
  .gitignore
  .idea/naver-checkstyle-rules.xml
  .idea/naver-checkstyle-supperssions.xml
  .idea/naver-intellij-formatter.xml
  bus-seat/.gitignore
  bus-seat/Dockerfile
  bus-seat/build.gradle
  bus-seat/gradle/wrapper/gradle-wrapper.jar
  bus-seat/gradle/wrapper/gradle-wrapper.properties
  bus-seat/gradlew
  bus-seat/gradlew.bat
  bus-seat/settings.gradle
  bus-seat/src/main/java/org/kernel360/busseat/BusSeatApplication.java
  bus-seat/src/main/resources/application.yaml
  bus-seat/src/test/java/org/kernel360/busseat/BusSeatApplicationTests.java
  data/.gitignore
  docker-compose.yaml
Labels: enhancement

#20 feat: 공공 데이터 csv 파일 DB Insert 구현
  README.md
  data/mysql-files/add_constraints.sql
  data/mysql-files/bulk_insert_routes.sql
  data/mysql-files/bulk_insert_stations.sql
  data/mysql-files/bus_route.csv
  data/mysql-files/bus_station.csv
  data/mysql-files/init_db.sql
  data/mysql-files/schema.sql
Labels: enhancement

#23 feat: open api 요청 코드 추가
  bus-seat/src/main/java/org/kernel360/busseat/schedule/ResultCode.java
  bus-seat/src/main/java/org/kernel360/busseat/schedule/service/ScheduledTask.java
Labels: enhancement

#24 Feature/#14 - API 관련 Entity 연동
  bus-seat/src/main/java/org/kernel360/busseat/route/controller/BusRouteController.java
  bus-seat/src/main/java/org/kernel360/busseat/route/entity/BusRouteEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/route/repository/BusRouteRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/route/service/BusRouteService.java
  bus-seat/src/main/java/org/kernel360/busseat/schedule/controller/BusLocationController.java
  bus-seat/src/main/java/org/kernel360/busseat/station/cotroller/BusStationController.java
  bus-seat/src/main/java/org/kernel360/busseat/station/entity/BusStationEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/station/repository/BusStationRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/station/service/BusStationService.java
Labels: enhancement

#27 [#25] 버스 및 정류장 검색 구현
  bus-seat/src/main/java/org/kernel360/busseat/route/controller/BusRouteController.java
  bus-seat/src/main/java/org/kernel360/busseat/route/dto/RouteDto.java
  bus-seat/src/main/java/org/kernel360/busseat/route/entity/BusRouteEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/route/repository/BusRouteRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/route/service/BusRouteService.java
  bus-seat/src/main/java/org/kernel360/busseat/station/cotroller/BusStationController.java
  bus-seat/src/main/java/org/kernel360/busseat/station/dto/StationDto.java
  bus-seat/src/main/java/org/kernel360/busseat/station/entity/BusStationEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/station/repository/BusStationRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/station/service/BusStationService.java
Labels: enhancement

#30 [#29] 테스트용 Location Dummy data 주입 sql 작성
  README.md
  data/mysql-files/bulk_insert_route_locations_dummy.sql
  data/mysql-files/bus_location_dummy_data.csv
Labels: enhancement

#42 [#31] 연관관계 추가
  bus-seat/src/main/java/org/kernel360/busseat/schedule/entity/BusLocationEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/station/entity/BusStationEntity.java
Labels: enhancement

#41 [#36] 인수인계 이전, 프로젝트 세팅 관련 README 업데이트
  .gitignore
  README.md
  docker-compose.yaml
Labels: documentation

#39 [#32] 사용자 요청 JPA 연동 / Insert API 구현
  bus-seat/src/main/java/org/kernel360/busseat/user_request/controller/UserRequestController.java
  bus-seat/src/main/java/org/kernel360/busseat/user_request/dto/UserRequestDto.java
  bus-seat/src/main/java/org/kernel360/busseat/user_request/entity/UserRequestEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/user_request/repository/UserRequestRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/user_request/service/UserRequestService.java
Labels: enhancement

#43 [#40] 경유 정류소 연관관계 설정
  bus-seat/src/main/java/org/kernel360/busseat/route/entity/BusRouteEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/route/repository/BusRouteRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/dto/RouteStationDto.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/entity/BusRouteStationEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/service/BusRouteStationService.java
  bus-seat/src/main/java/org/kernel360/busseat/station/entity/BusStationEntity.java
  data/mysql-files/schema.sql
Labels: enhancement

#49 [#47] Refactoring 작업 전 프로젝트 구조 변경 - refactor 필요한 부분 삭제
  bus-seat/build.gradle
  bus-seat/src/main/java/org/kernel360/busseat/openapi/dto/ApiProperties.java
  bus-seat/src/main/java/org/kernel360/busseat/openapi/dto/ApiResponse.java
  bus-seat/src/main/java/org/kernel360/busseat/openapi/dto/ResultCode.java
  bus-seat/src/main/java/org/kernel360/busseat/route_location/controller/BusLocationController.java
  bus-seat/src/main/java/org/kernel360/busseat/route_location/dto/BusRouteLocation.java
  bus-seat/src/main/java/org/kernel360/busseat/route_location/entity/BusRouteLocationEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/route_location/repository/BusRouteLocationRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/route_location/service/BusRouteLocationService.java
  bus-seat/src/main/java/org/kernel360/busseat/schedule/controller/BusLocationController.java
  bus-seat/src/main/java/org/kernel360/busseat/schedule/dto/BusLocation.java
  bus-seat/src/main/java/org/kernel360/busseat/schedule/dto/BusLocationDto.java
  bus-seat/src/main/java/org/kernel360/busseat/schedule/dto/MsgBody.java
  bus-seat/src/main/java/org/kernel360/busseat/schedule/dto/MsgHeader.java
  bus-seat/src/main/java/org/kernel360/busseat/schedule/repository/BusRouteLocationRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/schedule/service/BusLocationService.java
  bus-seat/src/main/java/org/kernel360/busseat/schedule/service/ScheduledTask.java
  bus-seat/src/main/java/org/kernel360/busseat/station/entity/BusStationEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/user_request/dto/UserRequestDto.java
  bus-seat/src/main/java/org/kernel360/busseat/user_request/entity/UserRequestEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/user_request/service/UserRequestService.java
  bus-seat/src/main/java/org/kernel360/busseat/view/controller/HomeController.java
  bus-seat/src/main/resources/static/css/bootstrap.min.css
  bus-seat/src/main/resources/templates/css/bootstrap.min.css
  bus-seat/src/main/resources/templates/home/busInfo.html
  data/mysql-files/schema.sql
Labels: enhancement

#50 [#48] 프론트엔드 개발 환경 세팅
  frontend/.babelrc
  frontend/.gitignore
  frontend/babel.config.js
  frontend/components.json
  frontend/config/webpack.common.js
  frontend/config/webpack.dev.js
  frontend/config/webpack.prod.js
  frontend/eslint.config.mjs
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/ErrorPage.tsx
  frontend/src/api/readme.md
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/form.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/pagination.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/separator.tsx
  frontend/src/global.css
  frontend/src/index.tsx
  frontend/src/lib/utils.ts
  frontend/src/tailwind.css
  frontend/tailwind.config.js
  frontend/tsconfig.json
Labels: good first issue

#57 [#54] RouteStation api 연동
  bus-seat/src/main/java/org/kernel360/busseat/openapi/configuration/BusRouteStationApiProperty.java
  bus-seat/src/main/java/org/kernel360/busseat/openapi/dto/BusRouteStationListBody.java
  bus-seat/src/main/java/org/kernel360/busseat/openapi/dto/BusRouteStationListResponse.java
  bus-seat/src/main/java/org/kernel360/busseat/openapi/dto/RouteInfoItemApiBody.java
  bus-seat/src/main/java/org/kernel360/busseat/openapi/service/AbstractOpenApiService.java
  bus-seat/src/main/java/org/kernel360/busseat/openapi/service/BusLocationApiService.java
  bus-seat/src/main/java/org/kernel360/busseat/openapi/service/BusRouteStationApiService.java
  bus-seat/src/main/java/org/kernel360/busseat/openapi/service/RouteInfoItemApiService.java
  bus-seat/src/main/java/org/kernel360/busseat/route/entity/BusRouteEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/route_info_item/entity/RouteInfoItemEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/route_info_item/service/RouteInfoItemService.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/dto/RouteStationDto.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/entity/BusRouteStationEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/repository/BusRouteStationRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/service/BusRouteStationService.java
  bus-seat/src/main/resources/application.yaml
  data/mysql-files/schema.sql
Labels: enhancement

#62 feat: #58 정류장 리스트 획득 API 작성
  bus-seat/src/main/java/org/kernel360/busseat/bus_location/repository/BusLocationRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/common/dto/Pagination.java
  bus-seat/src/main/java/org/kernel360/busseat/common/dto/PaginationDto.java
  bus-seat/src/main/java/org/kernel360/busseat/route/controller/BusRouteController.java
  bus-seat/src/main/java/org/kernel360/busseat/route/dto/StationsDto.java
  bus-seat/src/main/java/org/kernel360/busseat/route/service/BusRouteService.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/controller/BusRouteStationController.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/repository/BusRouteStationRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/service/BusRouteStationService.java
  bus-seat/src/main/java/org/kernel360/busseat/station/cotroller/BusStationController.java
  bus-seat/src/main/java/org/kernel360/busseat/station/repository/BusStationRepository.java
Labels: enhancement

#63 [#60] Station 삭제
  bus-seat/src/main/java/org/kernel360/busseat/bus_location/entity/BusLocationEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/dto/RouteStationDto.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/entity/BusRouteStationEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/route_station/service/BusRouteStationService.java
  bus-seat/src/main/java/org/kernel360/busseat/station/cotroller/BusStationController.java
  bus-seat/src/main/java/org/kernel360/busseat/station/dto/StationDto.java
  bus-seat/src/main/java/org/kernel360/busseat/station/entity/BusStationEntity.java
  bus-seat/src/main/java/org/kernel360/busseat/station/repository/BusStationRepository.java
  bus-seat/src/main/java/org/kernel360/busseat/station/service/BusStationService.java
  data/mysql-files/add_constraints.sql
  data/mysql-files/init_db.sql
  data/mysql-files/schema.sql
Labels: fix

#70 [#51,#52] 프론트엔드 프로토타입 구현 및 CORS origin 허용
  bus-seat/src/main/java/org/kernel360/busseat/WebConfig.java
  frontend/src/App.tsx
  frontend/src/api/API_URL.tsx
  frontend/src/api/GET_requestAvailableSeats.tsx
  frontend/src/api/GET_requestBusStationList.tsx
  frontend/src/api/GET_requestRouteList.tsx
  frontend/src/api/POST_requestNewRoute.tsx
  frontend/src/components/progessive-Input/SeatChartFinal.tsx
  frontend/src/components/progessive-Input/cardPerSteps/RouteSelection.tsx
  frontend/src/components/progessive-Input/cardPerSteps/StationsSelection.tsx
  frontend/src/components/progessive-Input/cardPerSteps/TimeSelection.tsx
  frontend/src/components/ui/carousel.tsx
  frontend/src/components/ui/chart.tsx
  frontend/src/components/ui/popover.tsx
  frontend/src/components/ui/scroll-area.tsx
  frontend/src/global.css
  frontend/src/pages/RouteStatisticsPage.tsx
Labels: enhancement
